# Generated by Django 3.0.7 on 2020-07-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200626_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('Email', models.CharField(default='', max_length=50)),
                ('Phone', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=50)),
                ('checkbox', models.BooleanField(default=False)),
            ],
        ),
    ]
